AllCops:
  TargetRubyVersion: 2.4
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'client/**/*'
    - 'node_modules/**/*'
    - 'lib/seed/**/*'

Rails:
  Enabled: true

Rails/InverseOf:
  Enabled: false

TrailingBlankLines:
  Enabled: true

Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Lint/MissingCopEnableDirective:
  Enabled: false
