const bodyParser = require('body-parser');
const express = require('express');
const favicon = require('serve-favicon');
const logger = require('morgan');
const path = require('path');

const auth = require('./utils/auth');
const { getToken, getUserFromToken, refreshToken, verifyToken } = auth;
const routes = require('./config/routes');

const app = express();

app.use(favicon(path.join(__dirname, '/client/public', 'favicon.ico')));
if (process.env.NODE_ENV !== 'production') app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(express.static(path.join(__dirname, '/dist')));
app.use('/static', express.static(path.join(__dirname, '/build/static')));
app.use('/images', express.static(path.join(__dirname, '/client/public/images')));

if (process.env.NODE_ENV === 'development') {
  app.use((req, res, next) => {
    // The dev server generated by create-react-app lives on localhost:5100, so we must allow cross origin requests from there
    res.setHeader('Access-Control-Allow-Origin', 'http://localhost:5100');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');
    res.setHeader('Access-Control-Allow-Headers', 'authorization,content-type,X-Requested-With');

    next();
  });
}

// This middleware verifies a possible token coming in from a request
// If there is a valid token, add the corresponding user to req.user and refreshes expiration date on token
// It also appends token to res.locals.token
app.use((req, res, next) => {
  const token = getToken(req);

  verifyToken(token)
    .then((verified) => {
      if (verified) {
        req.user = getUserFromToken(token);
        res.locals.token = refreshToken(req.user);
      }
      if (!verified) req.user = null;
      next();
    })
    .catch((err) => {
      console.error(err);
      req.user = null;
      next();
    });
});

// Api middleware assumes appends response (if successful) to res.locals.jsonResp
// Failed responses won't make it past this middleware
app.use('/api', routes(auth));

// After controllers attach response, combine with token and send
app.use('/api', (req, res) => {
  Object.keys(res.locals.jsonResp || {}).forEach((key) => {
    if (typeof res.locals.jsonResp[key] === 'undefined') {
      res.locals.jsonResp[key] = null;
    }
  });
  res.json(Object.assign({}, { token: res.locals.token }, res.locals.jsonResp || {}));
});

app.use((req, res) => {
  res.sendFile(path.resolve(__dirname, './build/index.html'));
});

exports.app = app;
