#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check 2>&1 >/dev/null || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }

  echo "==> Setup nginx config"
  brew setup-nginx-conf osumbchallenges . config/nginx.conf.erb
fi

npm install
npm install nodemon -g
