#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew update
  brew tap homebrew/bundle 2>/dev/null
fi

script/bootstrap

if psql -lqt | cut -d \| -f 1 | grep -w challenges_dev; then
  echo "Development database already exists, dropping"
  dropdb challenges_dev
fi

echo "===> Setting up development database..."
createdb challenges_dev

echo "==> Migrating development"
./node_modules/db-migrate/bin/db-migrate up --config config/database.json -m db/migrations

if psql -lqt | cut -d \| -f 1 | grep -w challenges_test; then
  echo "Testing database already exists, dropping"
  dropdb challenges_test
fi

echo "===> Setting up testing database..."
createdb challenges_test

echo "Testing database already exists, dropping"
./node_modules/db-migrate/bin/db-migrate up --config config/database.json -m db/migrations --env test

echo "==> App is now ready to go!"
