#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew update
  brew tap homebrew/bundle 2>/dev/null
fi

script/bootstrap

if psql -lqt | cut -d \| -f 1 | grep -w challenges_dev; then
  echo "Database already exists"
  echo "==> Removing previous database..."

  # remove surrounding whitespace
  dropdb "$(psql -lqt | cut -d \| -f 1 | grep -w challenges_dev | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
fi

echo "===> Setting up DB..."
createdb challenges_dev
npm run migrate:latest

if redis-cli ping | grep PONG; then
  echo "Redis server is running"
else
  echo "===> Setting up Redis server..."
  ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
fi

echo "==> App is now ready to go!"
