#!/bin/sh

# script/test: Do everything related to testing

set -e

cd "$(dirname "$0")/.."

export NODE_ENV="test"

echo "==> Linting..."
eslint .
echo "==> Done!"

# We'll do some integration tests later
echo "==> Setting Up Test Database..."
node db/load-test-data.js
echo "==> Done!"

echo "==> Running tests..."
jasmine

# THIS WILL NEED TO BE HERE! "test": "react-scripts test --env=jsdom",
