#!/bin/sh

# script/test: Do everything related to testing

set -e

cd "$(dirname "$0")/.."

export NODE_ENV="test"

echo "==> Linting..."
eslint .
echo "==> Done!"

if psql -lqt | cut -d \| -f 1 | grep -w challenges_test; then
  echo "Test database already exists"
  echo "==> Removing previous database..."

  # remove surrounding whitespace
  dropdb "$(psql -lqt | cut -d \| -f 1 | grep -w challenges_test | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
fi

echo "===> Setting up test DB..."
createdb challenges_test
npm run migrate:latest

# We'll do some integration tests later
echo "==> Loading test data..."
node db/load-test-data.js
echo "==> Done!"

echo "==> Running tests..."
jasmine
